print(" "*115 +"58, Ilupeju Street,")
print(" "* 100 + "Dolphin estate, Ikoyi lagos.")
print(" "*120 + "From: Dickson")
print("To: my students,")
print("All over the world.\n")
print("Dear Student,")
print(" "*10 + "I am happy you have decided to learn python. It is a powerful language and a fun")
print("language. I congratulate you on writing your first lines of code. You are meant for great ")
print("things and I believe in you.")
print(" "*10 +"I like this quote by Alcultis Turner \"The more you practice the better you’ll be, the")
print("harder you train the greater in you they’ll see\".")
print((" "*10 + "Dickson is proud of you.\n")*2)
print("Yours sincerly,")
print("Dickson.")
